routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::prefix('auth')->name('admin.auth.')->group(function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('remote/{user}/{token}', 'Auth\CustomController')->name('remote');
});


Route::name('admin.')->middleware('admin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('api', 'JamblerApiController')->names([
        'index' => 'jambler_api.index',
        'create' => 'jambler_api.create',
        'store' => 'jambler_api.store',
        'edit' => 'jambler_api.edit',
        'update' => 'jambler_api.update',
        'destroy' => 'jambler_api.delete',
    ]);
    Route::resource('answer', 'AnswerController')->names([
        'index' => 'answer.index',
        'create' => 'answer.create',
        'store' => 'answer.store',
        'edit' => 'answer.edit',
        'update' => 'answer.update',
        'destroy' => 'answer.delete',
    ]);
Route::get('api/{id}/default','JamblerApiController@defaultUpdate')->name('jambler_api.default');
    Route::resource('coupon', 'CouponController')->names([
        'index' => 'coupon.index',
        'create' => 'coupon.create',
        'store' => 'coupon.store',
        'edit' => 'coupon.edit',
        'update' => 'coupon.update',
        'destroy' => 'coupon.delete',
    ]);


    Route::get('telegram', 'TelegramSettingController@index')->name('telegram');
    Route::delete('image', 'SettingsController@deleteImage')->name('image');

    Route::post('telegram', 'TelegramSettingController@store');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::post('/telegram/{token}', 'Telegram\TelegramController@process')
    ->name('telegram.bot');
Route::name('main.')
    ->namespace('Main')
    ->group(function () {

        Route::get('/', 'MixerController@create')->name('index');
//        Route::get('/mix', 'MixerController@create')->name('mix');
        Route::post('/','MixerController@store')->name('store');
        Route::post('/download','MixerController@download')->name('guarantee');
    });

resources/views/admin/layout/layout.blade.php
@extends('template.layout.layout')


@section('sidebar')
	@include('admin.layout.sidebar')
@endsection

@section('navbar')
	@include('admin.layout.navbar')
@endsection

resources/views/admin/layout/navbar.blade.php
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-minimize">
			<button id="minimizeSidebar" class="btn btn-fill btn-icon"><i class="ti-more-alt"></i></button>
		</div>
		<div class="navbar-header">
			<button type="button" class="navbar-toggle">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar bar1"></span>
				<span class="icon-bar bar2"></span>
				<span class="icon-bar bar3"></span>
			</button>
			<a class="navbar-brand" href="#Dashboard">
				@yield('page-title')
			</a>
		</div>
		<div class="collapse navbar-collapse">


			<ul class="nav navbar-nav navbar-right">
{{--				<li class="{{ isActiveRoute('admin.news') }}">--}}
{{--					<a href="{{ route('admin.news') }}">--}}
{{--						<i class="ti-announcement"></i>--}}
{{--						<p>Новости</p>--}}
{{--					</a>--}}
{{--				</li>--}}
{{--				<li class="{{ isActiveRoute('admin.faq') }}">--}}
{{--					<a href="{{ route('admin.faq') }}">--}}
{{--						<i class="ti-info-alt"></i>--}}
{{--						<p>FAQ</p>--}}
{{--					</a>--}}
{{--				</li>--}}
{{--				<li class="{{ isActiveRoute('admin.settings') }}">--}}
{{--					<a href="{{ route('admin.settings') }}" class="btn-rotate">--}}
{{--						<i class="ti-settings"></i>--}}
{{--						Настройки--}}
{{--					</a>--}}
{{--				</li>--}}
{{--				<li>--}}
{{--					<a href="{{ route('admin.auth.logout') }}">--}}
{{--						<i class="ti-back-right"></i>--}}
{{--						<p>Выход</p>--}}
{{--					</a>--}}
{{--				</li>--}}

			</ul>
		</div>
	</div>
</nav>

resources/views/admin/layout/sidebar.blade.php
<div class="sidebar" data-background-color="brown" data-active-color="danger">
    <!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | brown"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->
    <div class="logo">
        <a href="{{ route('admin.dashboard') }}" class="simple-text logo-mini">
            M
        </a>

        <a href="{{ route('admin.dashboard') }}" class="simple-text logo-normal">
            Mixer
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="info">
                <div class="photo">
                    <img src="{{asset('admin-assets')}}/img/faces/face-2.jpg"/>
                </div>

                <a href="#">
	                        <span>
								{{ optional(auth('admin')->user())->username }}
							</span>
                </a>

            </div>
        </div>
        <ul class="nav">
            {{--            {{isActiveRoute('admin.dashboard', true)}}--}}
            <li class="">
                <a href="{{ route('admin.dashboard') }}">
                    <i class="ti-bar-chart-alt"></i>
                    <p>Главная</p>
                </a>
            </li>

            {{--			@can('viewAny',\App\Models\ApiKeys::class)--}}
            <li class="
{{--{{isActiveRoute('admin.jambler_api')}}--}}
                ">
                <a href="{{route('admin.jambler_api.index')}}">
                    <i class="ti-map"></i>
                    <p>Api keys</p>
                </a>
            </li>
            <li class="
                ">
                <a href="{{route('admin.coupon.index')}}">
                    <i class="ti-map"></i>
                    <p>Coupon</p>
                </a>
            </li>

            <li class="
">
                <a href="{{ route('admin.answer.index') }}">
                    <i class="ti-book"></i>
                    <p>Answers</p>
                </a>
            </li>

            <li class="
">
                <a href="{{ route('admin.telegram') }}">
                    <i class="ti-text"></i>
                    <p>Telegram</p>
                </a>
            </li>


        </ul>
    </div>
</div>