routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::prefix('auth')->name('admin.auth.')->group(function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('remote/{user}/{token}', 'Auth\CustomController')->name('remote');
});


Route::name('admin.')->middleware('admin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('api', 'JamblerApiController')->names([
        'index' => 'jambler_api.index',
        'create' => 'jambler_api.create',
        'store' => 'jambler_api.store',
        'edit' => 'jambler_api.edit',
        'update' => 'jambler_api.update',
        'destroy' => 'jambler_api.delete',
    ]);
    Route::resource('answer', 'AnswerController')->names([
        'index' => 'answer.index',
        'create' => 'answer.create',
        'store' => 'answer.store',
        'edit' => 'answer.edit',
        'update' => 'answer.update',
        'destroy' => 'answer.delete',
    ]);
Route::get('api/{id}/default','JamblerApiController@defaultUpdate')->name('jambler_api.default');
    Route::resource('coupon', 'CouponController')->names([
        'index' => 'coupon.index',
        'create' => 'coupon.create',
        'store' => 'coupon.store',
        'edit' => 'coupon.edit',
        'update' => 'coupon.update',
        'destroy' => 'coupon.delete',
    ]);


    Route::get('telegram', 'TelegramSettingController@index')->name('telegram');
    Route::delete('image', 'SettingsController@deleteImage')->name('image');

    Route::post('telegram', 'TelegramSettingController@store');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::post('/telegram/{token}', 'Telegram\TelegramController@process')
    ->name('telegram.bot');
Route::name('main.')
    ->namespace('Main')
    ->group(function () {

        Route::get('/', 'MixerController@create')->name('index');
//        Route::get('/mix', 'MixerController@create')->name('mix');
        Route::post('/','MixerController@store')->name('store');
        Route::post('/download','MixerController@download')->name('guarantee');
    });

app/Http/Controllers/Main/CouponController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use App\Services\Jambler\InfoService;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class CouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('coupon.index', (new InfoService())->info());
    }

    public function useCoupon()
    {

    }


}

app/Http/Controllers/Main/MixerController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use App\Requests\MixerRequest;
use App\Services\Jambler\InfoService;
use App\ViewModels\MixerListViewModel;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class MixerController extends Controller
{
    /**
     * @var InfoService
     */
    private InfoService $service;

    /**
     * MixerController constructor.
     *
     * @param InfoService $service
     */
    public function __construct(InfoService $service)
    {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $info = $this->service->info();
        return view('main.index', compact('info'));
    }

    public function create()
    {
        $info = $this->service->info();
        $error = '';
        return \view('main.index', new MixerListViewModel($info, $error));
    }

    public function store(MixerRequest $request)
    {
        $data = $request->validated();
        $coupon = $data['coupon'] ?? null;
        $order = $this->service->crud($data, $coupon);
        $info = $this->service->info($coupon);

        $error = $order->getErrorMessage();

        if ($order->hasError()) {
            return \view('main.index', compact('order', 'info', 'error'));
        }

        return \view('main.result', compact('order', 'info', 'error'));
    }

    public function download(Request $request)
    {

        header('Content-type: text/plain');
        header('Content-Disposition: attachment; filename="LetterGuarantee.txt"');
        echo $request['text'];
    }
}

resources/views/main/mix.blade.php
<?php
/**
 * @var $order \App\DDD\Jambler\Response\Order
 * @var $info  \App\DDD\Jambler\Response\Info
 */
?>
@extends('main.layout.layout')

@section('content')

    <section>
        <div class="container">

            <div class="text-center">
                <h1>Bitcoin Mixer&nbsp;2.0</h1>
                <p class="big mt-4 d-none d-sm-block">Get cleanest coins from<br>European, Asian and North American<br>cryptocurrency
                    stock exchanges</p>
                <p class="mt-5">Enter your Bitcoin forward to address below:</p>
            </div>
            <div class="row mt-3">
                <div class="m-auto col-12 col-sm-9 col-md-7 col-lg-5 col-xl-4 d-inline-block text-center">
                    @if($errors->any())
                        @foreach($errors->all() as $error)
                            <div class="color-red text-left">
                                {{ $error }}
                            </div>
                        @endforeach
                    @else
                        <div class="color-red text-left">
                            {{ $error }}
                        </div>
                    @endif

                    <form method="post" action="{{route('main.store')}}">
                        @csrf
                        <input type="text" class="form-control" name="forward_addr"
                               placeholder="Enter first address (mandatory)" required>

                        <input type="text" class="form-control mt-2" name="forward_addr2"
                               placeholder="Enter second address (optional)">
                        <input type="text" class="form-control" name="coupon"
                               placeholder="Enter coupon">

                        <div class="row mt-4">
                            <div class="col-12">
                                <button type="submit" name="submit_mix" class="btn btn-jam">Mix My Coins</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="text-center mt-5">
                <p>Your money will be returned in different parts to addresses specified above</p>
                <p>
                    Time of return will be {{$info['withdraw_max_timeout']}} hours
                    <span class="ml-2 mr-2">|</span>
                    Service fee: {{$info['mixer_fee_pct']}}% + {{$info['mixer_fix_fee']}} BTC
                    <span class="ml-2 mr-2">|</span>
                    A generated address is valid for {{$info['order_lifetime']}} days (See <a href="#">FAQ</a>)
                </p>
            </div>
        </div>
    </section>

@endsection

resources/views/main/result.blade.php
<?php
/**
 * @var $order \App\DDD\Jambler\Response\Order
 * @var $info  \App\DDD\Jambler\Response\Info
 */
?>
@extends('main.layout.layout')

@section('content')

    <section class="send_bitcoin mb-5">

        <div class="text-center mb-4">

            <form class="mt-4" action="{{route('main.guarantee')}}" method="POST">
                @csrf
                <input type="hidden" name="text" value="{{$order['guarantee']}}">
                <button type="submit" class="btn btn-yellow">
                    Скачать гарантийное письмо
                </button>
            </form>

        </div>

        <div class="blockin">

            <div class="bg_style_shadow">

                <div class="inside__send_bitcoin">


                    <div class="left__send_bitcoin">
                        <img src="jambler/libs/qrcode.php?text=bitcoin:{{$order['address']}}">
                    </div>



                    <div class="right__send_bitcoin">
                        <h4>
                            отправьте Биткоины на этот адрес
                            <span class="min_text">
											(min {{$info['min_amount']}}, max {{$info['max_amount']}} BTC)
										</span>
                        </h4>
                        <label for="bitcoin_address" class="label_copy">
                            <input type="text" id="bitcoin_address" value="{{$order['address']}}" name="bitcoin_address" class="input_copy" readonly>
                            <div class="icon_input_copy">
                                <span class="icon icon-copy"></span>
                            </div>
                        </label>
                        <div class="info">
                            Ваша сессия очистки биткойнов действительна в течение {{$info['withdraw_max_timeout']}} часов. Отправьте свои монеты на адрес депозита в течение этого срока. Мы запланируем выплату ваших новых чистых монет, как только ваш депозит получит 1 подтверждение.
                        </div>
                    </div>

                </div>

            </div>

        </div>
        <script>
            $(document).ready(function () {
                $('#loader').removeClass('d-none');
                var req = function () {
                    $.get('{{env('MAIN_SITE')}}/libs/blockchain-info.php?address= {{$order['address']}}').done(resp => {
                        resp = JSON.parse(resp);
                        if (resp.err) {
                            $('#blockchain_error').text(resp.err);
                            $('#blockchain_error').removeClass('d-none');
                            $('#loader').hide();
                        } else if (+resp.total_received === 0) {
                            setTimeout(req, 20000);
                        } else {
                            $('#loader').hide();
                            $('#blockchain_result span').text(
                                Math.round((resp.total_received / 100000000) * 100000) / 100000
                            );
                            $('#blockchain_result').removeClass('d-none');
                        }
                    });
                }
                req();
            });
        </script>
    </section>

    <section class="calc">

        <div class="blockin">

            <div class="bg_style_shadow">

                <div class="inside__calc">

                    <h4>
                        Калькулятор стоимости и комиссии
                    </h4>
                    <div class="row">

                        <div class="col-lg-6">
                            <div for="bitcoin_address" class="label_copy">
                                <label for="send" class="label_copy">
                                    Сумма, которую Вы хотите отправить
                                </label>
                                <input type="number" class="input_copy" name="you_send" value="" min="{{$info['min_amount']}}" max="{{$info['max_amount']}}" step=".001" required>

                                <div class="icon_input_copy">
                                    <span class="icon icon-copy"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div for="bitcoin_address" class="label_copy">
                                <label for="get" class="label_copy">
                                    Сумма, которую Вы получите после списания с комиссии
                                </label>
                                <b id="you_receive" class="input_copy">-{{$info['mixer_fix_fee']}}</b>
                                <div class="icon_input_copy">
                                    <span class="icon icon-copy"></span>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </section>

{{--
{{--                </div>--}}
{{--                <div class="mt-4 text-center">--}}
{{--                    <a href="{{route('main.index')}}" class="btn btn-jam btn-jam-white">Mix More Coins</a>--}}
{{--                </div>--}}
{{--                <div class="text-center mt-5">--}}
{{--                    <p>Your money will be returned in different parts to addresses specified above</p>--}}
{{--                    <p>--}}
{{--                        Time of return will be {{$info['withdraw_max_timeout']}} hours--}}
{{--                        <span class="ml-2 mr-2">|</span>--}}
{{--                        Service fee: {{$info['mixer_fee_pct']}}% + {{$info['mixer_fix_fee']}} BTC--}}
{{--                        <span class="ml-2 mr-2">|</span>--}}
{{--                        A generated address is valid for {{$info['order_lifetime']}} days (See <a href="#">FAQ</a>)--}}
{{--                    </p>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--                        <div class="mt-5">--}}
{{--                            <a name="calculator"></a>--}}
{{--                            <h2 class="text-center">Exact Value & Fee Calculator</h2>--}}

{{--                            <form class="mt-4" action="#" method="POST">--}}

{{--                                <div class="form-group row">--}}
{{--                                    <label class="col-2 col-form-label text-right">You send:</label>--}}
{{--                                    <div class="col-3">--}}
{{--                                        <div class="input-group">--}}
{{--                                            <input type="number" class="form-control text-right" name="you_send" value="" min="{{$info['min_amount']}}" max="{{$info['max_amount']}}" step=".001" required>--}}
{{--                                            <div class="input-group-append">--}}
{{--                                                <span class="input-group-text">BTC</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                    <p class="col-7 text-14">There is a field for entering a sum which a user wants to transfer, the same as above the QR code. It is also a link to the blockchain.info service</p>--}}
{{--                                </div>--}}

{{--                                <div class="form-group row">--}}
{{--                                    <label class="col-2 col-form-label text-right">You receive:</label>--}}
{{--                                    <div class="col-3 col-form-label text-right">--}}
{{--                                        <b id="you_receive"></b> BTC--}}
{{--                                    </div>--}}
{{--                                    <p class="col-7 text-14">Your commission is not more than {{$info['mixer_fee_pct']}}% and {{$info['mixer_fix_fee']}} BTC – the BTC value is calculated, the commission value is taken from a letter of guarantee</p>--}}
{{--                                </div>--}}


{{--                                <div id="calculate_btn" class="col-12 text-center">--}}
{{--                                    <button type="submit" name="submit_calculator" class="btn btn-jam btn-jam-white">Calculate</button>--}}
{{--                                </div>--}}

{{--                            </form>--}}

{{--                        </div>--}}
{{--    </section>--}}
@endsection